<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2017
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard'] 				= array('Felder definieren','Bitte wählen Sie die Felder aus, aus denen der MultiColumnWizard bestehen soll.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_fieldName'] 	= array('Feldname','Bitte geben sie einen Feldnamen ein');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_inputType'] 	= array('Feldtyp','Wählen Sie die Art des Feldes.');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_default'] 		= array('Standardwert','Standardwert übergeben');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_label'] 		= array('Bezeichnung,Beschreibung','Geben Sie die Feldbezeichnung, Feldbeschreibung ein z.B. MeinFeld,Meine Beschreibung');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_eval'] 		= array('Evaluierung','Geben Sie optionale Evaluierungs-Optionen ein (JSON-Objekt-Schreibweise) z.B. "maxlength":100,"mandatory":true  ');
$GLOBALS['TL_LANG']['tl_pct_customelement_attribute']['options_multiColumnWizard_options'] 		= array('Options','Geben Sie die Auswahloptionen ein als JSON-String ein z.B. "options":["hallo1","hallo2"] oder übergeben Sie einen options_callback: "options_callback":["myClass","myCallback"]');
